# Generated by Django 2.0.7 on 2018-11-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20170821_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='An image with a display order of zero will be the primary image for a service', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='servicerecommendation',
            name='ranking',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Determines order of the services. A service with a higher value will appear before one with a lower ranking.', verbose_name='Ranking'),
        ),
    ]
